### ISSUE TITLE
help

### ISSUE THREAD

**Issue by 06NinjaKid06** [lua-rocks/install-lua#1]
ok so using your tutorial how do install with github codespaces?

**Comment by lua-rocks** [comment]
I'm not sure if compiling all the necessary binaries inside the Codespaces container is a good idea, but you can try adding them into the container's repository, then setting up all the required dependencies and compiling. Here's an example `devcontainer.json`:

```json
{
	"image": "mcr.microsoft.com/devcontainers/universal:2",
	"features": {
		"ghcr.io/rocker-org/devcontainer-features/apt-packages:1": {
			"upgradePackages": true,
			"packages": "build-essential,libreadline-dev,unzip,libssl-dev"
		}
	}
}
```

**Comment by lua-rocks** [comment]
This solution is simpler and more correct, but the luarocks configuration might not be perfect:

```json
{
	"image": "mcr.microsoft.com/devcontainers/universal:2",
	"features": {
		"ghcr.io/rocker-org/devcontainer-features/apt-packages:1": {
			"upgradePackages": true,
			"packages": "lua5.3,luajit,luarocks"
		}
	}
}
```

**Comment by lua-rocks** [comment]
![изображение](https://github.com/lua-rocks/install-lua/assets/82697845/38d9b01a-5d70-44f8-8fd1-56ba9f101a5b)

**Comment by lua-rocks** [comment]
Sorry, I won't be able to provide more help as my knowledge about Codespaces is very limited.
